/**
 * This class is generated by jOOQ
 */
package com.markovlabs.eros.model;


import com.markovlabs.eros.model.tables.Dater;
import com.markovlabs.eros.model.tables.DatingMapping;
import com.markovlabs.eros.model.tables.EvaluationAnswers;
import com.markovlabs.eros.model.tables.Event;
import com.markovlabs.eros.model.tables.EventDaters;
import com.markovlabs.eros.model.tables.Image;
import com.markovlabs.eros.model.tables.Messages;
import com.markovlabs.eros.model.tables.ProfileAnswers;
import com.markovlabs.eros.model.tables.Question;
import com.markovlabs.eros.model.tables.Story;
import com.markovlabs.eros.model.tables.StoryAnswers;
import com.markovlabs.eros.model.tables.records.DaterRecord;
import com.markovlabs.eros.model.tables.records.DatingMappingRecord;
import com.markovlabs.eros.model.tables.records.EvaluationAnswersRecord;
import com.markovlabs.eros.model.tables.records.EventDatersRecord;
import com.markovlabs.eros.model.tables.records.EventRecord;
import com.markovlabs.eros.model.tables.records.ImageRecord;
import com.markovlabs.eros.model.tables.records.MessagesRecord;
import com.markovlabs.eros.model.tables.records.ProfileAnswersRecord;
import com.markovlabs.eros.model.tables.records.QuestionRecord;
import com.markovlabs.eros.model.tables.records.StoryAnswersRecord;
import com.markovlabs.eros.model.tables.records.StoryRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>eros</code> 
 * schema
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final Identity<DaterRecord, Long> IDENTITY_DATER = Identities0.IDENTITY_DATER;
	public static final Identity<DatingMappingRecord, Long> IDENTITY_DATING_MAPPING = Identities0.IDENTITY_DATING_MAPPING;
	public static final Identity<EvaluationAnswersRecord, Long> IDENTITY_EVALUATION_ANSWERS = Identities0.IDENTITY_EVALUATION_ANSWERS;
	public static final Identity<EventRecord, Long> IDENTITY_EVENT = Identities0.IDENTITY_EVENT;
	public static final Identity<EventDatersRecord, Long> IDENTITY_EVENT_DATERS = Identities0.IDENTITY_EVENT_DATERS;
	public static final Identity<ImageRecord, Long> IDENTITY_IMAGE = Identities0.IDENTITY_IMAGE;
	public static final Identity<MessagesRecord, Long> IDENTITY_MESSAGES = Identities0.IDENTITY_MESSAGES;
	public static final Identity<ProfileAnswersRecord, Long> IDENTITY_PROFILE_ANSWERS = Identities0.IDENTITY_PROFILE_ANSWERS;
	public static final Identity<QuestionRecord, Long> IDENTITY_QUESTION = Identities0.IDENTITY_QUESTION;
	public static final Identity<StoryRecord, Long> IDENTITY_STORY = Identities0.IDENTITY_STORY;
	public static final Identity<StoryAnswersRecord, Long> IDENTITY_STORY_ANSWERS = Identities0.IDENTITY_STORY_ANSWERS;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final UniqueKey<DaterRecord> KEY_DATER_PRIMARY = UniqueKeys0.KEY_DATER_PRIMARY;
	public static final UniqueKey<DatingMappingRecord> KEY_DATING_MAPPING_PRIMARY = UniqueKeys0.KEY_DATING_MAPPING_PRIMARY;
	public static final UniqueKey<EvaluationAnswersRecord> KEY_EVALUATION_ANSWERS_PRIMARY = UniqueKeys0.KEY_EVALUATION_ANSWERS_PRIMARY;
	public static final UniqueKey<EventRecord> KEY_EVENT_PRIMARY = UniqueKeys0.KEY_EVENT_PRIMARY;
	public static final UniqueKey<EventDatersRecord> KEY_EVENT_DATERS_PRIMARY = UniqueKeys0.KEY_EVENT_DATERS_PRIMARY;
	public static final UniqueKey<ImageRecord> KEY_IMAGE_PRIMARY = UniqueKeys0.KEY_IMAGE_PRIMARY;
	public static final UniqueKey<MessagesRecord> KEY_MESSAGES_PRIMARY = UniqueKeys0.KEY_MESSAGES_PRIMARY;
	public static final UniqueKey<ProfileAnswersRecord> KEY_PROFILE_ANSWERS_PRIMARY = UniqueKeys0.KEY_PROFILE_ANSWERS_PRIMARY;
	public static final UniqueKey<QuestionRecord> KEY_QUESTION_PRIMARY = UniqueKeys0.KEY_QUESTION_PRIMARY;
	public static final UniqueKey<StoryRecord> KEY_STORY_PRIMARY = UniqueKeys0.KEY_STORY_PRIMARY;
	public static final UniqueKey<StoryAnswersRecord> KEY_STORY_ANSWERS_PRIMARY = UniqueKeys0.KEY_STORY_ANSWERS_PRIMARY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final ForeignKey<EvaluationAnswersRecord, DaterRecord> DATER_ID_FK_6 = ForeignKeys0.DATER_ID_FK_6;
	public static final ForeignKey<EvaluationAnswersRecord, EventRecord> EVENT_ID_FK_6 = ForeignKeys0.EVENT_ID_FK_6;
	public static final ForeignKey<EvaluationAnswersRecord, DaterRecord> MATCH_ID_FK_1 = ForeignKeys0.MATCH_ID_FK_1;
	public static final ForeignKey<EvaluationAnswersRecord, QuestionRecord> QUESTION_ID_FK_2 = ForeignKeys0.QUESTION_ID_FK_2;
	public static final ForeignKey<EventRecord, DatingMappingRecord> DATING_MAPPING_FK_1 = ForeignKeys0.DATING_MAPPING_FK_1;
	public static final ForeignKey<EventDatersRecord, EventRecord> EVENT_ID_FK_1 = ForeignKeys0.EVENT_ID_FK_1;
	public static final ForeignKey<EventDatersRecord, DaterRecord> DATER_ID_FK_1 = ForeignKeys0.DATER_ID_FK_1;
	public static final ForeignKey<ImageRecord, DaterRecord> DATER_ID_FK_2 = ForeignKeys0.DATER_ID_FK_2;
	public static final ForeignKey<MessagesRecord, DaterRecord> DATER_ID_FK_7 = ForeignKeys0.DATER_ID_FK_7;
	public static final ForeignKey<MessagesRecord, DaterRecord> DATER_ID_FK_8 = ForeignKeys0.DATER_ID_FK_8;
	public static final ForeignKey<MessagesRecord, EventRecord> EVENT_ID_FK_7 = ForeignKeys0.EVENT_ID_FK_7;
	public static final ForeignKey<ProfileAnswersRecord, DaterRecord> DATER_ID_FK_10 = ForeignKeys0.DATER_ID_FK_10;
	public static final ForeignKey<ProfileAnswersRecord, QuestionRecord> QUESTION_ID_FK_1 = ForeignKeys0.QUESTION_ID_FK_1;
	public static final ForeignKey<StoryAnswersRecord, DaterRecord> DATERS_ID_FK_9 = ForeignKeys0.DATERS_ID_FK_9;
	public static final ForeignKey<StoryAnswersRecord, StoryRecord> STORY_ID_FK_1 = ForeignKeys0.STORY_ID_FK_1;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends AbstractKeys {
		public static Identity<DaterRecord, Long> IDENTITY_DATER = createIdentity(Dater.DATER, Dater.DATER.ID);
		public static Identity<DatingMappingRecord, Long> IDENTITY_DATING_MAPPING = createIdentity(DatingMapping.DATING_MAPPING, DatingMapping.DATING_MAPPING.ID);
		public static Identity<EvaluationAnswersRecord, Long> IDENTITY_EVALUATION_ANSWERS = createIdentity(EvaluationAnswers.EVALUATION_ANSWERS, EvaluationAnswers.EVALUATION_ANSWERS.ID);
		public static Identity<EventRecord, Long> IDENTITY_EVENT = createIdentity(Event.EVENT, Event.EVENT.ID);
		public static Identity<EventDatersRecord, Long> IDENTITY_EVENT_DATERS = createIdentity(EventDaters.EVENT_DATERS, EventDaters.EVENT_DATERS.ID);
		public static Identity<ImageRecord, Long> IDENTITY_IMAGE = createIdentity(Image.IMAGE, Image.IMAGE.ID);
		public static Identity<MessagesRecord, Long> IDENTITY_MESSAGES = createIdentity(Messages.MESSAGES, Messages.MESSAGES.ID);
		public static Identity<ProfileAnswersRecord, Long> IDENTITY_PROFILE_ANSWERS = createIdentity(ProfileAnswers.PROFILE_ANSWERS, ProfileAnswers.PROFILE_ANSWERS.ID);
		public static Identity<QuestionRecord, Long> IDENTITY_QUESTION = createIdentity(Question.QUESTION, Question.QUESTION.ID);
		public static Identity<StoryRecord, Long> IDENTITY_STORY = createIdentity(Story.STORY, Story.STORY.ID);
		public static Identity<StoryAnswersRecord, Long> IDENTITY_STORY_ANSWERS = createIdentity(StoryAnswers.STORY_ANSWERS, StoryAnswers.STORY_ANSWERS.ID);
	}

	private static class UniqueKeys0 extends AbstractKeys {
		public static final UniqueKey<DaterRecord> KEY_DATER_PRIMARY = createUniqueKey(Dater.DATER, Dater.DATER.ID);
		public static final UniqueKey<DatingMappingRecord> KEY_DATING_MAPPING_PRIMARY = createUniqueKey(DatingMapping.DATING_MAPPING, DatingMapping.DATING_MAPPING.ID);
		public static final UniqueKey<EvaluationAnswersRecord> KEY_EVALUATION_ANSWERS_PRIMARY = createUniqueKey(EvaluationAnswers.EVALUATION_ANSWERS, EvaluationAnswers.EVALUATION_ANSWERS.ID);
		public static final UniqueKey<EventRecord> KEY_EVENT_PRIMARY = createUniqueKey(Event.EVENT, Event.EVENT.ID);
		public static final UniqueKey<EventDatersRecord> KEY_EVENT_DATERS_PRIMARY = createUniqueKey(EventDaters.EVENT_DATERS, EventDaters.EVENT_DATERS.ID);
		public static final UniqueKey<ImageRecord> KEY_IMAGE_PRIMARY = createUniqueKey(Image.IMAGE, Image.IMAGE.ID);
		public static final UniqueKey<MessagesRecord> KEY_MESSAGES_PRIMARY = createUniqueKey(Messages.MESSAGES, Messages.MESSAGES.ID);
		public static final UniqueKey<ProfileAnswersRecord> KEY_PROFILE_ANSWERS_PRIMARY = createUniqueKey(ProfileAnswers.PROFILE_ANSWERS, ProfileAnswers.PROFILE_ANSWERS.ID);
		public static final UniqueKey<QuestionRecord> KEY_QUESTION_PRIMARY = createUniqueKey(Question.QUESTION, Question.QUESTION.ID);
		public static final UniqueKey<StoryRecord> KEY_STORY_PRIMARY = createUniqueKey(Story.STORY, Story.STORY.ID);
		public static final UniqueKey<StoryAnswersRecord> KEY_STORY_ANSWERS_PRIMARY = createUniqueKey(StoryAnswers.STORY_ANSWERS, StoryAnswers.STORY_ANSWERS.ID);
	}

	private static class ForeignKeys0 extends AbstractKeys {
		public static final ForeignKey<EvaluationAnswersRecord, DaterRecord> DATER_ID_FK_6 = createForeignKey(com.markovlabs.eros.model.Keys.KEY_DATER_PRIMARY, EvaluationAnswers.EVALUATION_ANSWERS, EvaluationAnswers.EVALUATION_ANSWERS.DATER_ID);
		public static final ForeignKey<EvaluationAnswersRecord, EventRecord> EVENT_ID_FK_6 = createForeignKey(com.markovlabs.eros.model.Keys.KEY_EVENT_PRIMARY, EvaluationAnswers.EVALUATION_ANSWERS, EvaluationAnswers.EVALUATION_ANSWERS.EVENT_ID);
		public static final ForeignKey<EvaluationAnswersRecord, DaterRecord> MATCH_ID_FK_1 = createForeignKey(com.markovlabs.eros.model.Keys.KEY_DATER_PRIMARY, EvaluationAnswers.EVALUATION_ANSWERS, EvaluationAnswers.EVALUATION_ANSWERS.MATCH_ID);
		public static final ForeignKey<EvaluationAnswersRecord, QuestionRecord> QUESTION_ID_FK_2 = createForeignKey(com.markovlabs.eros.model.Keys.KEY_QUESTION_PRIMARY, EvaluationAnswers.EVALUATION_ANSWERS, EvaluationAnswers.EVALUATION_ANSWERS.QUESTION_ID);
		public static final ForeignKey<EventRecord, DatingMappingRecord> DATING_MAPPING_FK_1 = createForeignKey(com.markovlabs.eros.model.Keys.KEY_DATING_MAPPING_PRIMARY, Event.EVENT, Event.EVENT.MAPPING_ID);
		public static final ForeignKey<EventDatersRecord, EventRecord> EVENT_ID_FK_1 = createForeignKey(com.markovlabs.eros.model.Keys.KEY_EVENT_PRIMARY, EventDaters.EVENT_DATERS, EventDaters.EVENT_DATERS.EVENT_ID);
		public static final ForeignKey<EventDatersRecord, DaterRecord> DATER_ID_FK_1 = createForeignKey(com.markovlabs.eros.model.Keys.KEY_DATER_PRIMARY, EventDaters.EVENT_DATERS, EventDaters.EVENT_DATERS.DATER_ID);
		public static final ForeignKey<ImageRecord, DaterRecord> DATER_ID_FK_2 = createForeignKey(com.markovlabs.eros.model.Keys.KEY_DATER_PRIMARY, Image.IMAGE, Image.IMAGE.DATER_ID);
		public static final ForeignKey<MessagesRecord, DaterRecord> DATER_ID_FK_7 = createForeignKey(com.markovlabs.eros.model.Keys.KEY_DATER_PRIMARY, Messages.MESSAGES, Messages.MESSAGES.FROM_DATER_ID);
		public static final ForeignKey<MessagesRecord, DaterRecord> DATER_ID_FK_8 = createForeignKey(com.markovlabs.eros.model.Keys.KEY_DATER_PRIMARY, Messages.MESSAGES, Messages.MESSAGES.TO_DATER_ID);
		public static final ForeignKey<MessagesRecord, EventRecord> EVENT_ID_FK_7 = createForeignKey(com.markovlabs.eros.model.Keys.KEY_EVENT_PRIMARY, Messages.MESSAGES, Messages.MESSAGES.EVENT_ID);
		public static final ForeignKey<ProfileAnswersRecord, DaterRecord> DATER_ID_FK_10 = createForeignKey(com.markovlabs.eros.model.Keys.KEY_DATER_PRIMARY, ProfileAnswers.PROFILE_ANSWERS, ProfileAnswers.PROFILE_ANSWERS.DATER_ID);
		public static final ForeignKey<ProfileAnswersRecord, QuestionRecord> QUESTION_ID_FK_1 = createForeignKey(com.markovlabs.eros.model.Keys.KEY_QUESTION_PRIMARY, ProfileAnswers.PROFILE_ANSWERS, ProfileAnswers.PROFILE_ANSWERS.QUESTION_ID);
		public static final ForeignKey<StoryAnswersRecord, DaterRecord> DATERS_ID_FK_9 = createForeignKey(com.markovlabs.eros.model.Keys.KEY_DATER_PRIMARY, StoryAnswers.STORY_ANSWERS, StoryAnswers.STORY_ANSWERS.DATER_ID);
		public static final ForeignKey<StoryAnswersRecord, StoryRecord> STORY_ID_FK_1 = createForeignKey(com.markovlabs.eros.model.Keys.KEY_STORY_PRIMARY, StoryAnswers.STORY_ANSWERS, StoryAnswers.STORY_ANSWERS.STORY_ID);
	}
}
