/**
 * This class is generated by jOOQ
 */
package com.markovlabs.eros.model;


import com.markovlabs.eros.model.tables.Dater;
import com.markovlabs.eros.model.tables.DatingMapping;
import com.markovlabs.eros.model.tables.EvaluationAnswers;
import com.markovlabs.eros.model.tables.Event;
import com.markovlabs.eros.model.tables.EventDaters;
import com.markovlabs.eros.model.tables.EventStories;
import com.markovlabs.eros.model.tables.Image;
import com.markovlabs.eros.model.tables.Messages;
import com.markovlabs.eros.model.tables.ProfileAnswers;
import com.markovlabs.eros.model.tables.Question;
import com.markovlabs.eros.model.tables.Story;
import com.markovlabs.eros.model.tables.StoryAnswers;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in eros
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table eros.DATER
	 */
	public static final Dater DATER = com.markovlabs.eros.model.tables.Dater.DATER;

	/**
	 * The table eros.DATING_MAPPING
	 */
	public static final DatingMapping DATING_MAPPING = com.markovlabs.eros.model.tables.DatingMapping.DATING_MAPPING;

	/**
	 * The table eros.EVALUATION_ANSWERS
	 */
	public static final EvaluationAnswers EVALUATION_ANSWERS = com.markovlabs.eros.model.tables.EvaluationAnswers.EVALUATION_ANSWERS;

	/**
	 * The table eros.EVENT
	 */
	public static final Event EVENT = com.markovlabs.eros.model.tables.Event.EVENT;

	/**
	 * The table eros.EVENT_DATERS
	 */
	public static final EventDaters EVENT_DATERS = com.markovlabs.eros.model.tables.EventDaters.EVENT_DATERS;

	/**
	 * The table eros.EVENT_STORIES
	 */
	public static final EventStories EVENT_STORIES = com.markovlabs.eros.model.tables.EventStories.EVENT_STORIES;

	/**
	 * The table eros.IMAGE
	 */
	public static final Image IMAGE = com.markovlabs.eros.model.tables.Image.IMAGE;

	/**
	 * The table eros.MESSAGES
	 */
	public static final Messages MESSAGES = com.markovlabs.eros.model.tables.Messages.MESSAGES;

	/**
	 * The table eros.PROFILE_ANSWERS
	 */
	public static final ProfileAnswers PROFILE_ANSWERS = com.markovlabs.eros.model.tables.ProfileAnswers.PROFILE_ANSWERS;

	/**
	 * The table eros.QUESTION
	 */
	public static final Question QUESTION = com.markovlabs.eros.model.tables.Question.QUESTION;

	/**
	 * The table eros.STORY
	 */
	public static final Story STORY = com.markovlabs.eros.model.tables.Story.STORY;

	/**
	 * The table eros.STORY_ANSWERS
	 */
	public static final StoryAnswers STORY_ANSWERS = com.markovlabs.eros.model.tables.StoryAnswers.STORY_ANSWERS;
}
