/**
 * This class is generated by jOOQ
 */
package com.markovlabs.eros.model.enums;


import javax.annotation.Generated;

import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum QuestionPageType implements EnumType {

	Consent_Page("Consent Page"),

	Acceptance_Page("Acceptance Page"),

	Profile_Creation("Profile Creation"),

	Profile_Evaluation("Profile Evaluation"),

	Messaging_Evaluation("Messaging Evaluation");

	private final String literal;

	private QuestionPageType(String literal) {
		this.literal = literal;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Schema getSchema() {
		return null;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String getName() {
		return "QUESTION_PAGE_TYPE";
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String getLiteral() {
		return literal;
	}
}
