/**
 * This class is generated by jOOQ
 */
package com.markovlabs.eros.model.tables.records;


import com.markovlabs.eros.model.enums.DaterGender;
import com.markovlabs.eros.model.tables.Dater;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DaterRecord extends UpdatableRecordImpl<DaterRecord> implements Record8<Long, String, String, String, DaterGender, Byte, Byte, Byte> {

	private static final long serialVersionUID = 149310864;

	/**
	 * Setter for <code>eros.DATER.ID</code>.
	 */
	public void setId(Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>eros.DATER.ID</code>.
	 */
	public Long getId() {
		return (Long) getValue(0);
	}

	/**
	 * Setter for <code>eros.DATER.EMAIL</code>.
	 */
	public void setEmail(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>eros.DATER.EMAIL</code>.
	 */
	public String getEmail() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>eros.DATER.PWD</code>.
	 */
	public void setPwd(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>eros.DATER.PWD</code>.
	 */
	public String getPwd() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>eros.DATER.NAME</code>.
	 */
	public void setName(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>eros.DATER.NAME</code>.
	 */
	public String getName() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>eros.DATER.GENDER</code>.
	 */
	public void setGender(DaterGender value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>eros.DATER.GENDER</code>.
	 */
	public DaterGender getGender() {
		return (DaterGender) getValue(4);
	}

	/**
	 * Setter for <code>eros.DATER.ACCEPT_CONSENT_PAGE_FLAG</code>.
	 */
	public void setAcceptConsentPageFlag(Byte value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>eros.DATER.ACCEPT_CONSENT_PAGE_FLAG</code>.
	 */
	public Byte getAcceptConsentPageFlag() {
		return (Byte) getValue(5);
	}

	/**
	 * Setter for <code>eros.DATER.ACCEPTANCE_QUESTION_PAGE_FLAG</code>.
	 */
	public void setAcceptanceQuestionPageFlag(Byte value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>eros.DATER.ACCEPTANCE_QUESTION_PAGE_FLAG</code>.
	 */
	public Byte getAcceptanceQuestionPageFlag() {
		return (Byte) getValue(6);
	}

	/**
	 * Setter for <code>eros.DATER.REJECTED</code>.
	 */
	public void setRejected(Byte value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>eros.DATER.REJECTED</code>.
	 */
	public Byte getRejected() {
		return (Byte) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Long> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<Long, String, String, String, DaterGender, Byte, Byte, Byte> fieldsRow() {
		return (Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<Long, String, String, String, DaterGender, Byte, Byte, Byte> valuesRow() {
		return (Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field1() {
		return Dater.DATER.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Dater.DATER.EMAIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Dater.DATER.PWD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return Dater.DATER.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<DaterGender> field5() {
		return Dater.DATER.GENDER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Byte> field6() {
		return Dater.DATER.ACCEPT_CONSENT_PAGE_FLAG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Byte> field7() {
		return Dater.DATER.ACCEPTANCE_QUESTION_PAGE_FLAG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Byte> field8() {
		return Dater.DATER.REJECTED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getEmail();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getPwd();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DaterGender value5() {
		return getGender();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Byte value6() {
		return getAcceptConsentPageFlag();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Byte value7() {
		return getAcceptanceQuestionPageFlag();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Byte value8() {
		return getRejected();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DaterRecord value1(Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DaterRecord value2(String value) {
		setEmail(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DaterRecord value3(String value) {
		setPwd(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DaterRecord value4(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DaterRecord value5(DaterGender value) {
		setGender(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DaterRecord value6(Byte value) {
		setAcceptConsentPageFlag(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DaterRecord value7(Byte value) {
		setAcceptanceQuestionPageFlag(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DaterRecord value8(Byte value) {
		setRejected(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DaterRecord values(Long value1, String value2, String value3, String value4, DaterGender value5, Byte value6, Byte value7, Byte value8) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached DaterRecord
	 */
	public DaterRecord() {
		super(Dater.DATER);
	}

	/**
	 * Create a detached, initialised DaterRecord
	 */
	public DaterRecord(Long id, String email, String pwd, String name, DaterGender gender, Byte acceptConsentPageFlag, Byte acceptanceQuestionPageFlag, Byte rejected) {
		super(Dater.DATER);

		setValue(0, id);
		setValue(1, email);
		setValue(2, pwd);
		setValue(3, name);
		setValue(4, gender);
		setValue(5, acceptConsentPageFlag);
		setValue(6, acceptanceQuestionPageFlag);
		setValue(7, rejected);
	}
}
