/**
 * This class is generated by jOOQ
 */
package com.markovlabs.eros.model.tables.records;


import com.markovlabs.eros.model.enums.DaterGender;
import com.markovlabs.eros.model.tables.Dater;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DaterRecord extends UpdatableRecordImpl<DaterRecord> implements Record11<Long, String, String, String, String, String, DaterGender, Byte, Byte, Byte, Byte> {

	private static final long serialVersionUID = 81354724;

	/**
	 * Setter for <code>eros.DATER.ID</code>.
	 */
	public void setId(Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>eros.DATER.ID</code>.
	 */
	public Long getId() {
		return (Long) getValue(0);
	}

	/**
	 * Setter for <code>eros.DATER.EMAIL</code>.
	 */
	public void setEmail(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>eros.DATER.EMAIL</code>.
	 */
	public String getEmail() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>eros.DATER.PWD</code>.
	 */
	public void setPwd(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>eros.DATER.PWD</code>.
	 */
	public String getPwd() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>eros.DATER.PROFILE_NAME</code>.
	 */
	public void setProfileName(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>eros.DATER.PROFILE_NAME</code>.
	 */
	public String getProfileName() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>eros.DATER.NAME</code>.
	 */
	public void setName(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>eros.DATER.NAME</code>.
	 */
	public String getName() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>eros.DATER.LAST_NAME</code>.
	 */
	public void setLastName(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>eros.DATER.LAST_NAME</code>.
	 */
	public String getLastName() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>eros.DATER.GENDER</code>.
	 */
	public void setGender(DaterGender value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>eros.DATER.GENDER</code>.
	 */
	public DaterGender getGender() {
		return (DaterGender) getValue(6);
	}

	/**
	 * Setter for <code>eros.DATER.ACCEPT_CONSENT_PAGE_FLAG</code>.
	 */
	public void setAcceptConsentPageFlag(Byte value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>eros.DATER.ACCEPT_CONSENT_PAGE_FLAG</code>.
	 */
	public Byte getAcceptConsentPageFlag() {
		return (Byte) getValue(7);
	}

	/**
	 * Setter for <code>eros.DATER.ACCEPTANCE_QUESTION_PAGE_FLAG</code>.
	 */
	public void setAcceptanceQuestionPageFlag(Byte value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>eros.DATER.ACCEPTANCE_QUESTION_PAGE_FLAG</code>.
	 */
	public Byte getAcceptanceQuestionPageFlag() {
		return (Byte) getValue(8);
	}

	/**
	 * Setter for <code>eros.DATER.PROFILE_CREATION_PAGE_FLAG</code>.
	 */
	public void setProfileCreationPageFlag(Byte value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>eros.DATER.PROFILE_CREATION_PAGE_FLAG</code>.
	 */
	public Byte getProfileCreationPageFlag() {
		return (Byte) getValue(9);
	}

	/**
	 * Setter for <code>eros.DATER.REJECTED</code>.
	 */
	public void setRejected(Byte value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>eros.DATER.REJECTED</code>.
	 */
	public Byte getRejected() {
		return (Byte) getValue(10);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Long> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record11 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row11<Long, String, String, String, String, String, DaterGender, Byte, Byte, Byte, Byte> fieldsRow() {
		return (Row11) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row11<Long, String, String, String, String, String, DaterGender, Byte, Byte, Byte, Byte> valuesRow() {
		return (Row11) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field1() {
		return Dater.DATER.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Dater.DATER.EMAIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Dater.DATER.PWD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return Dater.DATER.PROFILE_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return Dater.DATER.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return Dater.DATER.LAST_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<DaterGender> field7() {
		return Dater.DATER.GENDER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Byte> field8() {
		return Dater.DATER.ACCEPT_CONSENT_PAGE_FLAG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Byte> field9() {
		return Dater.DATER.ACCEPTANCE_QUESTION_PAGE_FLAG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Byte> field10() {
		return Dater.DATER.PROFILE_CREATION_PAGE_FLAG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Byte> field11() {
		return Dater.DATER.REJECTED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getEmail();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getPwd();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getProfileName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getLastName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DaterGender value7() {
		return getGender();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Byte value8() {
		return getAcceptConsentPageFlag();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Byte value9() {
		return getAcceptanceQuestionPageFlag();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Byte value10() {
		return getProfileCreationPageFlag();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Byte value11() {
		return getRejected();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DaterRecord value1(Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DaterRecord value2(String value) {
		setEmail(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DaterRecord value3(String value) {
		setPwd(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DaterRecord value4(String value) {
		setProfileName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DaterRecord value5(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DaterRecord value6(String value) {
		setLastName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DaterRecord value7(DaterGender value) {
		setGender(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DaterRecord value8(Byte value) {
		setAcceptConsentPageFlag(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DaterRecord value9(Byte value) {
		setAcceptanceQuestionPageFlag(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DaterRecord value10(Byte value) {
		setProfileCreationPageFlag(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DaterRecord value11(Byte value) {
		setRejected(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DaterRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, DaterGender value7, Byte value8, Byte value9, Byte value10, Byte value11) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached DaterRecord
	 */
	public DaterRecord() {
		super(Dater.DATER);
	}

	/**
	 * Create a detached, initialised DaterRecord
	 */
	public DaterRecord(Long id, String email, String pwd, String profileName, String name, String lastName, DaterGender gender, Byte acceptConsentPageFlag, Byte acceptanceQuestionPageFlag, Byte profileCreationPageFlag, Byte rejected) {
		super(Dater.DATER);

		setValue(0, id);
		setValue(1, email);
		setValue(2, pwd);
		setValue(3, profileName);
		setValue(4, name);
		setValue(5, lastName);
		setValue(6, gender);
		setValue(7, acceptConsentPageFlag);
		setValue(8, acceptanceQuestionPageFlag);
		setValue(9, profileCreationPageFlag);
		setValue(10, rejected);
	}
}
