/**
 * This class is generated by jOOQ
 */
package com.markovlabs.eros.model.tables.records;


import com.markovlabs.eros.model.tables.EvaluationAnswers;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EvaluationAnswersRecord extends UpdatableRecordImpl<EvaluationAnswersRecord> implements Record6<Long, Long, Long, Long, Long, String> {

	private static final long serialVersionUID = -232172151;

	/**
	 * Setter for <code>eros.EVALUATION_ANSWERS.ID</code>.
	 */
	public void setId(Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>eros.EVALUATION_ANSWERS.ID</code>.
	 */
	public Long getId() {
		return (Long) getValue(0);
	}

	/**
	 * Setter for <code>eros.EVALUATION_ANSWERS.DATER_ID</code>.
	 */
	public void setDaterId(Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>eros.EVALUATION_ANSWERS.DATER_ID</code>.
	 */
	public Long getDaterId() {
		return (Long) getValue(1);
	}

	/**
	 * Setter for <code>eros.EVALUATION_ANSWERS.EVENT_ID</code>.
	 */
	public void setEventId(Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>eros.EVALUATION_ANSWERS.EVENT_ID</code>.
	 */
	public Long getEventId() {
		return (Long) getValue(2);
	}

	/**
	 * Setter for <code>eros.EVALUATION_ANSWERS.MATCH_ID</code>.
	 */
	public void setMatchId(Long value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>eros.EVALUATION_ANSWERS.MATCH_ID</code>.
	 */
	public Long getMatchId() {
		return (Long) getValue(3);
	}

	/**
	 * Setter for <code>eros.EVALUATION_ANSWERS.QUESTION_ID</code>.
	 */
	public void setQuestionId(Long value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>eros.EVALUATION_ANSWERS.QUESTION_ID</code>.
	 */
	public Long getQuestionId() {
		return (Long) getValue(4);
	}

	/**
	 * Setter for <code>eros.EVALUATION_ANSWERS.ANSWER</code>.
	 */
	public void setAnswer(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>eros.EVALUATION_ANSWERS.ANSWER</code>.
	 */
	public String getAnswer() {
		return (String) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Long> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Long, Long, Long, Long, Long, String> fieldsRow() {
		return (Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Long, Long, Long, Long, Long, String> valuesRow() {
		return (Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field1() {
		return EvaluationAnswers.EVALUATION_ANSWERS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field2() {
		return EvaluationAnswers.EVALUATION_ANSWERS.DATER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field3() {
		return EvaluationAnswers.EVALUATION_ANSWERS.EVENT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field4() {
		return EvaluationAnswers.EVALUATION_ANSWERS.MATCH_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field5() {
		return EvaluationAnswers.EVALUATION_ANSWERS.QUESTION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return EvaluationAnswers.EVALUATION_ANSWERS.ANSWER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value2() {
		return getDaterId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value3() {
		return getEventId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value4() {
		return getMatchId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value5() {
		return getQuestionId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getAnswer();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EvaluationAnswersRecord value1(Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EvaluationAnswersRecord value2(Long value) {
		setDaterId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EvaluationAnswersRecord value3(Long value) {
		setEventId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EvaluationAnswersRecord value4(Long value) {
		setMatchId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EvaluationAnswersRecord value5(Long value) {
		setQuestionId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EvaluationAnswersRecord value6(String value) {
		setAnswer(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EvaluationAnswersRecord values(Long value1, Long value2, Long value3, Long value4, Long value5, String value6) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached EvaluationAnswersRecord
	 */
	public EvaluationAnswersRecord() {
		super(EvaluationAnswers.EVALUATION_ANSWERS);
	}

	/**
	 * Create a detached, initialised EvaluationAnswersRecord
	 */
	public EvaluationAnswersRecord(Long id, Long daterId, Long eventId, Long matchId, Long questionId, String answer) {
		super(EvaluationAnswers.EVALUATION_ANSWERS);

		setValue(0, id);
		setValue(1, daterId);
		setValue(2, eventId);
		setValue(3, matchId);
		setValue(4, questionId);
		setValue(5, answer);
	}
}
