/**
 * This class is generated by jOOQ
 */
package com.markovlabs.eros.model.tables.records;


import com.markovlabs.eros.model.enums.EventStoriesLabel;
import com.markovlabs.eros.model.tables.EventStories;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EventStoriesRecord extends UpdatableRecordImpl<EventStoriesRecord> implements Record4<Long, Long, Long, EventStoriesLabel> {

	private static final long serialVersionUID = -1919186434;

	/**
	 * Setter for <code>eros.EVENT_STORIES.ID</code>.
	 */
	public void setId(Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>eros.EVENT_STORIES.ID</code>.
	 */
	public Long getId() {
		return (Long) getValue(0);
	}

	/**
	 * Setter for <code>eros.EVENT_STORIES.EVENT_ID</code>.
	 */
	public void setEventId(Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>eros.EVENT_STORIES.EVENT_ID</code>.
	 */
	public Long getEventId() {
		return (Long) getValue(1);
	}

	/**
	 * Setter for <code>eros.EVENT_STORIES.STORY_ID</code>.
	 */
	public void setStoryId(Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>eros.EVENT_STORIES.STORY_ID</code>.
	 */
	public Long getStoryId() {
		return (Long) getValue(2);
	}

	/**
	 * Setter for <code>eros.EVENT_STORIES.LABEL</code>.
	 */
	public void setLabel(EventStoriesLabel value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>eros.EVENT_STORIES.LABEL</code>.
	 */
	public EventStoriesLabel getLabel() {
		return (EventStoriesLabel) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Long> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Long, Long, Long, EventStoriesLabel> fieldsRow() {
		return (Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Long, Long, Long, EventStoriesLabel> valuesRow() {
		return (Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field1() {
		return EventStories.EVENT_STORIES.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field2() {
		return EventStories.EVENT_STORIES.EVENT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field3() {
		return EventStories.EVENT_STORIES.STORY_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<EventStoriesLabel> field4() {
		return EventStories.EVENT_STORIES.LABEL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value2() {
		return getEventId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value3() {
		return getStoryId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventStoriesLabel value4() {
		return getLabel();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventStoriesRecord value1(Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventStoriesRecord value2(Long value) {
		setEventId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventStoriesRecord value3(Long value) {
		setStoryId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventStoriesRecord value4(EventStoriesLabel value) {
		setLabel(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventStoriesRecord values(Long value1, Long value2, Long value3, EventStoriesLabel value4) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached EventStoriesRecord
	 */
	public EventStoriesRecord() {
		super(EventStories.EVENT_STORIES);
	}

	/**
	 * Create a detached, initialised EventStoriesRecord
	 */
	public EventStoriesRecord(Long id, Long eventId, Long storyId, EventStoriesLabel label) {
		super(EventStories.EVENT_STORIES);

		setValue(0, id);
		setValue(1, eventId);
		setValue(2, storyId);
		setValue(3, label);
	}
}
