/**
 * This class is generated by jOOQ
 */
package com.markovlabs.eros.model.tables.records;


import com.markovlabs.eros.model.tables.Messages;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MessagesRecord extends UpdatableRecordImpl<MessagesRecord> implements Record6<Long, Long, Long, Long, String, Timestamp> {

	private static final long serialVersionUID = -1439681625;

	/**
	 * Setter for <code>eros.MESSAGES.FROM_DATER_ID</code>.
	 */
	public void setFromDaterId(Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>eros.MESSAGES.FROM_DATER_ID</code>.
	 */
	public Long getFromDaterId() {
		return (Long) getValue(0);
	}

	/**
	 * Setter for <code>eros.MESSAGES.TO_DATER_ID</code>.
	 */
	public void setToDaterId(Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>eros.MESSAGES.TO_DATER_ID</code>.
	 */
	public Long getToDaterId() {
		return (Long) getValue(1);
	}

	/**
	 * Setter for <code>eros.MESSAGES.ID</code>.
	 */
	public void setId(Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>eros.MESSAGES.ID</code>.
	 */
	public Long getId() {
		return (Long) getValue(2);
	}

	/**
	 * Setter for <code>eros.MESSAGES.EVENT_ID</code>.
	 */
	public void setEventId(Long value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>eros.MESSAGES.EVENT_ID</code>.
	 */
	public Long getEventId() {
		return (Long) getValue(3);
	}

	/**
	 * Setter for <code>eros.MESSAGES.CONTENT</code>.
	 */
	public void setContent(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>eros.MESSAGES.CONTENT</code>.
	 */
	public String getContent() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>eros.MESSAGES.TIME_RECEIVED</code>.
	 */
	public void setTimeReceived(Timestamp value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>eros.MESSAGES.TIME_RECEIVED</code>.
	 */
	public Timestamp getTimeReceived() {
		return (Timestamp) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Long> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Long, Long, Long, Long, String, Timestamp> fieldsRow() {
		return (Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Long, Long, Long, Long, String, Timestamp> valuesRow() {
		return (Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field1() {
		return Messages.MESSAGES.FROM_DATER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field2() {
		return Messages.MESSAGES.TO_DATER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field3() {
		return Messages.MESSAGES.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field4() {
		return Messages.MESSAGES.EVENT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return Messages.MESSAGES.CONTENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field6() {
		return Messages.MESSAGES.TIME_RECEIVED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value1() {
		return getFromDaterId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value2() {
		return getToDaterId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value3() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value4() {
		return getEventId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getContent();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value6() {
		return getTimeReceived();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MessagesRecord value1(Long value) {
		setFromDaterId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MessagesRecord value2(Long value) {
		setToDaterId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MessagesRecord value3(Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MessagesRecord value4(Long value) {
		setEventId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MessagesRecord value5(String value) {
		setContent(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MessagesRecord value6(Timestamp value) {
		setTimeReceived(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MessagesRecord values(Long value1, Long value2, Long value3, Long value4, String value5, Timestamp value6) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached MessagesRecord
	 */
	public MessagesRecord() {
		super(Messages.MESSAGES);
	}

	/**
	 * Create a detached, initialised MessagesRecord
	 */
	public MessagesRecord(Long fromDaterId, Long toDaterId, Long id, Long eventId, String content, Timestamp timeReceived) {
		super(Messages.MESSAGES);

		setValue(0, fromDaterId);
		setValue(1, toDaterId);
		setValue(2, id);
		setValue(3, eventId);
		setValue(4, content);
		setValue(5, timeReceived);
	}
}
