/**
 * This class is generated by jOOQ
 */
package com.markovlabs.eros.model.tables.records;


import com.markovlabs.eros.model.tables.ProfileAnswers;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProfileAnswersRecord extends UpdatableRecordImpl<ProfileAnswersRecord> implements Record4<Long, Long, Long, String> {

	private static final long serialVersionUID = -881493191;

	/**
	 * Setter for <code>eros.PROFILE_ANSWERS.ID</code>.
	 */
	public void setId(Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>eros.PROFILE_ANSWERS.ID</code>.
	 */
	public Long getId() {
		return (Long) getValue(0);
	}

	/**
	 * Setter for <code>eros.PROFILE_ANSWERS.DATER_ID</code>.
	 */
	public void setDaterId(Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>eros.PROFILE_ANSWERS.DATER_ID</code>.
	 */
	public Long getDaterId() {
		return (Long) getValue(1);
	}

	/**
	 * Setter for <code>eros.PROFILE_ANSWERS.QUESTION_ID</code>.
	 */
	public void setQuestionId(Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>eros.PROFILE_ANSWERS.QUESTION_ID</code>.
	 */
	public Long getQuestionId() {
		return (Long) getValue(2);
	}

	/**
	 * Setter for <code>eros.PROFILE_ANSWERS.ANSWER</code>.
	 */
	public void setAnswer(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>eros.PROFILE_ANSWERS.ANSWER</code>.
	 */
	public String getAnswer() {
		return (String) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Long> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Long, Long, Long, String> fieldsRow() {
		return (Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Long, Long, Long, String> valuesRow() {
		return (Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field1() {
		return ProfileAnswers.PROFILE_ANSWERS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field2() {
		return ProfileAnswers.PROFILE_ANSWERS.DATER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field3() {
		return ProfileAnswers.PROFILE_ANSWERS.QUESTION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return ProfileAnswers.PROFILE_ANSWERS.ANSWER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value2() {
		return getDaterId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value3() {
		return getQuestionId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getAnswer();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProfileAnswersRecord value1(Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProfileAnswersRecord value2(Long value) {
		setDaterId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProfileAnswersRecord value3(Long value) {
		setQuestionId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProfileAnswersRecord value4(String value) {
		setAnswer(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProfileAnswersRecord values(Long value1, Long value2, Long value3, String value4) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ProfileAnswersRecord
	 */
	public ProfileAnswersRecord() {
		super(ProfileAnswers.PROFILE_ANSWERS);
	}

	/**
	 * Create a detached, initialised ProfileAnswersRecord
	 */
	public ProfileAnswersRecord(Long id, Long daterId, Long questionId, String answer) {
		super(ProfileAnswers.PROFILE_ANSWERS);

		setValue(0, id);
		setValue(1, daterId);
		setValue(2, questionId);
		setValue(3, answer);
	}
}
