/**
 * This class is generated by jOOQ
 */
package com.markovlabs.eros.model.tables.records;


import com.markovlabs.eros.model.enums.QuestionPageType;
import com.markovlabs.eros.model.tables.Question;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QuestionRecord extends UpdatableRecordImpl<QuestionRecord> implements Record3<Long, String, QuestionPageType> {

	private static final long serialVersionUID = 2045250301;

	/**
	 * Setter for <code>eros.QUESTION.ID</code>.
	 */
	public void setId(Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>eros.QUESTION.ID</code>.
	 */
	public Long getId() {
		return (Long) getValue(0);
	}

	/**
	 * Setter for <code>eros.QUESTION.CONTENT</code>.
	 */
	public void setContent(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>eros.QUESTION.CONTENT</code>.
	 */
	public String getContent() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>eros.QUESTION.PAGE_TYPE</code>.
	 */
	public void setPageType(QuestionPageType value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>eros.QUESTION.PAGE_TYPE</code>.
	 */
	public QuestionPageType getPageType() {
		return (QuestionPageType) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Long> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Long, String, QuestionPageType> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Long, String, QuestionPageType> valuesRow() {
		return (Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field1() {
		return Question.QUESTION.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Question.QUESTION.CONTENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<QuestionPageType> field3() {
		return Question.QUESTION.PAGE_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getContent();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public QuestionPageType value3() {
		return getPageType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public QuestionRecord value1(Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public QuestionRecord value2(String value) {
		setContent(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public QuestionRecord value3(QuestionPageType value) {
		setPageType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public QuestionRecord values(Long value1, String value2, QuestionPageType value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached QuestionRecord
	 */
	public QuestionRecord() {
		super(Question.QUESTION);
	}

	/**
	 * Create a detached, initialised QuestionRecord
	 */
	public QuestionRecord(Long id, String content, QuestionPageType pageType) {
		super(Question.QUESTION);

		setValue(0, id);
		setValue(1, content);
		setValue(2, pageType);
	}
}
