/**
 * This class is generated by jOOQ
 */
package com.markovlabs.eros.model.tables.records;


import com.markovlabs.eros.model.enums.StoryAnswersAnswer;
import com.markovlabs.eros.model.tables.StoryAnswers;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StoryAnswersRecord extends UpdatableRecordImpl<StoryAnswersRecord> implements Record4<Long, Long, Long, StoryAnswersAnswer> {

	private static final long serialVersionUID = 138625260;

	/**
	 * Setter for <code>eros.STORY_ANSWERS.ID</code>.
	 */
	public void setId(Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>eros.STORY_ANSWERS.ID</code>.
	 */
	public Long getId() {
		return (Long) getValue(0);
	}

	/**
	 * Setter for <code>eros.STORY_ANSWERS.DATER_ID</code>.
	 */
	public void setDaterId(Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>eros.STORY_ANSWERS.DATER_ID</code>.
	 */
	public Long getDaterId() {
		return (Long) getValue(1);
	}

	/**
	 * Setter for <code>eros.STORY_ANSWERS.STORY_ID</code>.
	 */
	public void setStoryId(Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>eros.STORY_ANSWERS.STORY_ID</code>.
	 */
	public Long getStoryId() {
		return (Long) getValue(2);
	}

	/**
	 * Setter for <code>eros.STORY_ANSWERS.ANSWER</code>.
	 */
	public void setAnswer(StoryAnswersAnswer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>eros.STORY_ANSWERS.ANSWER</code>.
	 */
	public StoryAnswersAnswer getAnswer() {
		return (StoryAnswersAnswer) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Long> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Long, Long, Long, StoryAnswersAnswer> fieldsRow() {
		return (Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Long, Long, Long, StoryAnswersAnswer> valuesRow() {
		return (Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field1() {
		return StoryAnswers.STORY_ANSWERS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field2() {
		return StoryAnswers.STORY_ANSWERS.DATER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field3() {
		return StoryAnswers.STORY_ANSWERS.STORY_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<StoryAnswersAnswer> field4() {
		return StoryAnswers.STORY_ANSWERS.ANSWER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value2() {
		return getDaterId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value3() {
		return getStoryId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StoryAnswersAnswer value4() {
		return getAnswer();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StoryAnswersRecord value1(Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StoryAnswersRecord value2(Long value) {
		setDaterId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StoryAnswersRecord value3(Long value) {
		setStoryId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StoryAnswersRecord value4(StoryAnswersAnswer value) {
		setAnswer(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StoryAnswersRecord values(Long value1, Long value2, Long value3, StoryAnswersAnswer value4) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached StoryAnswersRecord
	 */
	public StoryAnswersRecord() {
		super(StoryAnswers.STORY_ANSWERS);
	}

	/**
	 * Create a detached, initialised StoryAnswersRecord
	 */
	public StoryAnswersRecord(Long id, Long daterId, Long storyId, StoryAnswersAnswer answer) {
		super(StoryAnswers.STORY_ANSWERS);

		setValue(0, id);
		setValue(1, daterId);
		setValue(2, storyId);
		setValue(3, answer);
	}
}
