/**
 * This class is generated by jOOQ
 */
package com.markovlabs.eros.model.tables.records;


import com.markovlabs.eros.model.enums.StoryStoryType;
import com.markovlabs.eros.model.tables.Story;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StoryRecord extends UpdatableRecordImpl<StoryRecord> implements Record6<Long, String, StoryStoryType, String, String, String> {

	private static final long serialVersionUID = -1313129262;

	/**
	 * Setter for <code>eros.STORY.ID</code>.
	 */
	public void setId(Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>eros.STORY.ID</code>.
	 */
	public Long getId() {
		return (Long) getValue(0);
	}

	/**
	 * Setter for <code>eros.STORY.CONTENT</code>.
	 */
	public void setContent(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>eros.STORY.CONTENT</code>.
	 */
	public String getContent() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>eros.STORY.STORY_TYPE</code>.
	 */
	public void setStoryType(StoryStoryType value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>eros.STORY.STORY_TYPE</code>.
	 */
	public StoryStoryType getStoryType() {
		return (StoryStoryType) getValue(2);
	}

	/**
	 * Setter for <code>eros.STORY.QUESTION</code>.
	 */
	public void setQuestion(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>eros.STORY.QUESTION</code>.
	 */
	public String getQuestion() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>eros.STORY.ANSWER_A</code>.
	 */
	public void setAnswerA(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>eros.STORY.ANSWER_A</code>.
	 */
	public String getAnswerA() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>eros.STORY.ANSWER_B</code>.
	 */
	public void setAnswerB(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>eros.STORY.ANSWER_B</code>.
	 */
	public String getAnswerB() {
		return (String) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Long> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Long, String, StoryStoryType, String, String, String> fieldsRow() {
		return (Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Long, String, StoryStoryType, String, String, String> valuesRow() {
		return (Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field1() {
		return Story.STORY.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Story.STORY.CONTENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<StoryStoryType> field3() {
		return Story.STORY.STORY_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return Story.STORY.QUESTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return Story.STORY.ANSWER_A;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return Story.STORY.ANSWER_B;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getContent();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StoryStoryType value3() {
		return getStoryType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getQuestion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getAnswerA();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getAnswerB();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StoryRecord value1(Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StoryRecord value2(String value) {
		setContent(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StoryRecord value3(StoryStoryType value) {
		setStoryType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StoryRecord value4(String value) {
		setQuestion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StoryRecord value5(String value) {
		setAnswerA(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StoryRecord value6(String value) {
		setAnswerB(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StoryRecord values(Long value1, String value2, StoryStoryType value3, String value4, String value5, String value6) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached StoryRecord
	 */
	public StoryRecord() {
		super(Story.STORY);
	}

	/**
	 * Create a detached, initialised StoryRecord
	 */
	public StoryRecord(Long id, String content, StoryStoryType storyType, String question, String answerA, String answerB) {
		super(Story.STORY);

		setValue(0, id);
		setValue(1, content);
		setValue(2, storyType);
		setValue(3, question);
		setValue(4, answerA);
		setValue(5, answerB);
	}
}
