/**
 * This class is generated by jOOQ
 */
package com.markovlabs.eros.model.tables;


import com.markovlabs.eros.model.Eros;
import com.markovlabs.eros.model.Keys;
import com.markovlabs.eros.model.tables.records.EventRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Event extends TableImpl<EventRecord> {

	private static final long serialVersionUID = -2011303839;

	/**
	 * The reference instance of <code>eros.EVENT</code>
	 */
	public static final Event EVENT = new Event();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<EventRecord> getRecordType() {
		return EventRecord.class;
	}

	/**
	 * The column <code>eros.EVENT.ID</code>.
	 */
	public final TableField<EventRecord, Long> ID = createField("ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>eros.EVENT.EVENT_DATE</code>.
	 */
	public final TableField<EventRecord, String> EVENT_DATE = createField("EVENT_DATE", org.jooq.impl.SQLDataType.VARCHAR.length(10), this, "");

	/**
	 * The column <code>eros.EVENT.LOCATION</code>.
	 */
	public final TableField<EventRecord, String> LOCATION = createField("LOCATION", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>eros.EVENT.NAME</code>.
	 */
	public final TableField<EventRecord, String> NAME = createField("NAME", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

	/**
	 * The column <code>eros.EVENT.STARTED</code>.
	 */
	public final TableField<EventRecord, Byte> STARTED = createField("STARTED", org.jooq.impl.SQLDataType.TINYINT.defaulted(true), this, "");

	/**
	 * The column <code>eros.EVENT.ENDED</code>.
	 */
	public final TableField<EventRecord, Byte> ENDED = createField("ENDED", org.jooq.impl.SQLDataType.TINYINT.defaulted(true), this, "");

	/**
	 * The column <code>eros.EVENT.MAPPING_ID</code>.
	 */
	public final TableField<EventRecord, Long> MAPPING_ID = createField("MAPPING_ID", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * Create a <code>eros.EVENT</code> table reference
	 */
	public Event() {
		this("EVENT", null);
	}

	/**
	 * Create an aliased <code>eros.EVENT</code> table reference
	 */
	public Event(String alias) {
		this(alias, EVENT);
	}

	private Event(String alias, Table<EventRecord> aliased) {
		this(alias, aliased, null);
	}

	private Event(String alias, Table<EventRecord> aliased, Field<?>[] parameters) {
		super(alias, Eros.EROS, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<EventRecord, Long> getIdentity() {
		return Keys.IDENTITY_EVENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<EventRecord> getPrimaryKey() {
		return Keys.KEY_EVENT_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<EventRecord>> getKeys() {
		return Arrays.<UniqueKey<EventRecord>>asList(Keys.KEY_EVENT_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<EventRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<EventRecord, ?>>asList(Keys.DATING_MAPPING_FK_1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Event as(String alias) {
		return new Event(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Event rename(String name) {
		return new Event(name, null);
	}
}
