/**
 * This class is generated by jOOQ
 */
package com.markovlabs.eros.model.tables;


import com.markovlabs.eros.model.Eros;
import com.markovlabs.eros.model.Keys;
import com.markovlabs.eros.model.tables.records.EventDatersRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EventDaters extends TableImpl<EventDatersRecord> {

	private static final long serialVersionUID = 1412648318;

	/**
	 * The reference instance of <code>eros.EVENT_DATERS</code>
	 */
	public static final EventDaters EVENT_DATERS = new EventDaters();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<EventDatersRecord> getRecordType() {
		return EventDatersRecord.class;
	}

	/**
	 * The column <code>eros.EVENT_DATERS.ID</code>.
	 */
	public final TableField<EventDatersRecord, Long> ID = createField("ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>eros.EVENT_DATERS.EVENT_ID</code>.
	 */
	public final TableField<EventDatersRecord, Long> EVENT_ID = createField("EVENT_ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>eros.EVENT_DATERS.DATER_ID</code>.
	 */
	public final TableField<EventDatersRecord, Long> DATER_ID = createField("DATER_ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>eros.EVENT_DATERS.PROFILE_EVALUATION_COMPLETED_FLAG</code>.
	 */
	public final TableField<EventDatersRecord, Byte> PROFILE_EVALUATION_COMPLETED_FLAG = createField("PROFILE_EVALUATION_COMPLETED_FLAG", org.jooq.impl.SQLDataType.TINYINT.defaulted(true), this, "");

	/**
	 * The column <code>eros.EVENT_DATERS.MESSAGING_EVALUATION_COMPLETED_FLAG</code>.
	 */
	public final TableField<EventDatersRecord, Byte> MESSAGING_EVALUATION_COMPLETED_FLAG = createField("MESSAGING_EVALUATION_COMPLETED_FLAG", org.jooq.impl.SQLDataType.TINYINT.defaulted(true), this, "");

	/**
	 * Create a <code>eros.EVENT_DATERS</code> table reference
	 */
	public EventDaters() {
		this("EVENT_DATERS", null);
	}

	/**
	 * Create an aliased <code>eros.EVENT_DATERS</code> table reference
	 */
	public EventDaters(String alias) {
		this(alias, EVENT_DATERS);
	}

	private EventDaters(String alias, Table<EventDatersRecord> aliased) {
		this(alias, aliased, null);
	}

	private EventDaters(String alias, Table<EventDatersRecord> aliased, Field<?>[] parameters) {
		super(alias, Eros.EROS, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<EventDatersRecord, Long> getIdentity() {
		return Keys.IDENTITY_EVENT_DATERS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<EventDatersRecord> getPrimaryKey() {
		return Keys.KEY_EVENT_DATERS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<EventDatersRecord>> getKeys() {
		return Arrays.<UniqueKey<EventDatersRecord>>asList(Keys.KEY_EVENT_DATERS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<EventDatersRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<EventDatersRecord, ?>>asList(Keys.EVENT_ID_FK_1, Keys.DATER_ID_FK_1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventDaters as(String alias) {
		return new EventDaters(alias, this);
	}

	/**
	 * Rename this table
	 */
	public EventDaters rename(String name) {
		return new EventDaters(name, null);
	}
}
