/**
 * This class is generated by jOOQ
 */
package com.markovlabs.eros.model.tables;


import com.markovlabs.eros.model.Eros;
import com.markovlabs.eros.model.Keys;
import com.markovlabs.eros.model.enums.StoryStoryType;
import com.markovlabs.eros.model.tables.records.StoryRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Story extends TableImpl<StoryRecord> {

	private static final long serialVersionUID = 582910000;

	/**
	 * The reference instance of <code>eros.STORY</code>
	 */
	public static final Story STORY = new Story();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<StoryRecord> getRecordType() {
		return StoryRecord.class;
	}

	/**
	 * The column <code>eros.STORY.ID</code>.
	 */
	public final TableField<StoryRecord, Long> ID = createField("ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>eros.STORY.CONTENT</code>.
	 */
	public final TableField<StoryRecord, String> CONTENT = createField("CONTENT", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>eros.STORY.STORY_TYPE</code>.
	 */
	public final TableField<StoryRecord, StoryStoryType> STORY_TYPE = createField("STORY_TYPE", org.jooq.util.mysql.MySQLDataType.VARCHAR.asEnumDataType(com.markovlabs.eros.model.enums.StoryStoryType.class), this, "");

	/**
	 * The column <code>eros.STORY.QUESTION</code>.
	 */
	public final TableField<StoryRecord, String> QUESTION = createField("QUESTION", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>eros.STORY.ANSWER_A</code>.
	 */
	public final TableField<StoryRecord, String> ANSWER_A = createField("ANSWER_A", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>eros.STORY.ANSWER_B</code>.
	 */
	public final TableField<StoryRecord, String> ANSWER_B = createField("ANSWER_B", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * Create a <code>eros.STORY</code> table reference
	 */
	public Story() {
		this("STORY", null);
	}

	/**
	 * Create an aliased <code>eros.STORY</code> table reference
	 */
	public Story(String alias) {
		this(alias, STORY);
	}

	private Story(String alias, Table<StoryRecord> aliased) {
		this(alias, aliased, null);
	}

	private Story(String alias, Table<StoryRecord> aliased, Field<?>[] parameters) {
		super(alias, Eros.EROS, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<StoryRecord, Long> getIdentity() {
		return Keys.IDENTITY_STORY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<StoryRecord> getPrimaryKey() {
		return Keys.KEY_STORY_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<StoryRecord>> getKeys() {
		return Arrays.<UniqueKey<StoryRecord>>asList(Keys.KEY_STORY_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Story as(String alias) {
		return new Story(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Story rename(String name) {
		return new Story(name, null);
	}
}
